In [7]:
import numpy as np
import matplotlib.pyplot as plt


nlinear_x0 = np.empty((2000,2))
nlinear_x1 = np.empty((2000,2))


with open("nonlinear_vectorfield_data_x0.txt") as f:
    line = f.readline()
    cnt = 0
    while line:
        x01, x02 = str(line).split(" ")
        nlinear_x0[cnt, 0] = float(x01)
        nlinear_x0[cnt, 1] = float(x02)
        cnt = cnt + 1
        line = f.readline()
        
with open("nonlinear_vectorfield_data_x1.txt") as f:
    line = f.readline()
    cnt = 0
    while line:
        x11, x12 = str(line).split(" ")
        nlinear_x1[cnt, 0] = float(x11)
        nlinear_x1[cnt, 1] = float(x12)
        cnt = cnt + 1
        line = f.readline()

'''set \Delta t to be 0.1'''
diff=nlinear_x1-nlinear_x0
vhat=diff/0.1

num=30
xcenter=np.linspace(-4.5,4.5,num)
ycenter=np.linspace(-4.5,4.5,num)

def phi_l(x, xc, ep):
    return np.exp(-((x[0]-xc[0])**2+(x[1]-xc[1])**2)/ep**2)

def phi_mat(xs, xcenter, ycenter, ep, num):
    result=np.empty((2000,num**2))
    for i in range(num):
        for j in range(num):
            for k in range(2000):
                result[k, num*i+j]=phi_l(xs[k], [xcenter[i],ycenter[j]], ep)
    return result

phis= phi_mat(nlinear_x0, xcenter, ycenter, 0.1, num)
C=np.linalg.lstsq(phis, vhat, rcond=None)[0]

fhat=np.dot(phis,C)
esti=np.empty((2000,2))

for i in range(2000):
    for j in range(2):
        esti[i][j]=nlinear_x0[i][j]+fhat[i][j]*0.1
esti

array([[-0.7944744 ,  2.10080101],
       [-4.17256668, -1.97929709],
       [-3.24637322, -3.62137125],
       ...,
       [ 4.14915632,  1.86717647],
       [-1.61959714, -3.78185524],
       [ 0.76096541,  2.14619919]])

In [8]:
nlinear_x1

array([[-0.79317039,  2.09824395],
       [-4.20066645, -1.95521799],
       [-3.32344627, -3.54971712],
       ...,
       [ 3.93738073,  1.83673157],
       [-1.79153043, -3.59123607],
       [ 0.78836138,  2.17869936]])

In [9]:
sum(sum((esti - nlinear_x1)**2))

14.588122449816044

In [10]:
nlinear_x0

array([[-0.74680196,  1.98292044],
       [-4.49897063, -1.77900685],
       [-3.17919698, -3.66895265],
       ...,
       [ 4.24798326,  1.88436412],
       [-1.56682152, -3.8390385 ],
       [ 0.71763342,  2.10165316]])

In [11]:
num=50
xcenter=np.linspace(-4.5,4.5,num)
ycenter=np.linspace(-4.5,4.5,num)

def phi_l(x, xc, ep):
    return np.exp(-((x[0]-xc[0])**2+(x[1]-xc[1])**2)/ep**2)

def phi_mat(xs, xcenter, ycenter, ep, num):
    result=np.empty((2000,num**2))
    for i in range(num):
        for j in range(num):
            for k in range(2000):
                result[k, num*i+j]=phi_l(xs[k], [xcenter[i],ycenter[j]], ep)
    return result

phis= phi_mat(nlinear_x0, xcenter, ycenter, 0.1, num)
C=np.linalg.lstsq(phis, vhat, rcond=None)[0]

fhat=np.dot(phis,C)
esti=np.empty((2000,2))

for i in range(2000):
    for j in range(2):
        esti[i][j]=nlinear_x0[i][j]+fhat[i][j]*0.1
esti

array([[-0.79317039,  2.09824395],
       [-4.20066645, -1.95521799],
       [-3.32344627, -3.54971712],
       ...,
       [ 3.93738073,  1.83673157],
       [-1.79153043, -3.59123607],
       [ 0.78836138,  2.17869936]])

In [12]:
sum(sum((esti - nlinear_x1)**2))

2.639018098148659e-17

In [13]:
num=100
xcenter=np.linspace(-4.5,4.5,num)
ycenter=np.linspace(-4.5,4.5,num)

def phi_l(x, xc, ep):
    return np.exp(-((x[0]-xc[0])**2+(x[1]-xc[1])**2)/ep**2)

def phi_mat(xs, xcenter, ycenter, ep, num):
    result=np.empty((2000,num**2))
    for i in range(num):
        for j in range(num):
            for k in range(2000):
                result[k, num*i+j]=phi_l(xs[k], [xcenter[i],ycenter[j]], ep)
    return result

phis= phi_mat(nlinear_x0, xcenter, ycenter, 0.1, num)
C=np.linalg.lstsq(phis, vhat, rcond=None)[0]

fhat=np.dot(phis,C)
esti=np.empty((2000,2))

for i in range(2000):
    for j in range(2):
        esti[i][j]=nlinear_x0[i][j]+fhat[i][j]*0.1
esti

array([[-0.79317039,  2.09824395],
       [-4.20066645, -1.95521799],
       [-3.32344627, -3.54971712],
       ...,
       [ 3.93738073,  1.83673157],
       [-1.79153043, -3.59123607],
       [ 0.78836138,  2.17869936]])

In [14]:
sum(sum((esti - nlinear_x1)**2))

2.0528871725942368e-27